// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2lxcqVnxO6AV_G4t6PUS6Sg44E1-1aCk',
    appId: '1:50269195141:web:13d46ca8f0cfefa97152ec',
    messagingSenderId: '50269195141',
    projectId: 'task3-2d664',
    authDomain: 'task3-2d664.firebaseapp.com',
    storageBucket: 'task3-2d664.appspot.com',
    measurementId: 'G-L5KNX8D02J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRVnHBTcCdEbXZyIqvYuhyZJo7MSwC4z4',
    appId: '1:50269195141:android:308d440174027db97152ec',
    messagingSenderId: '50269195141',
    projectId: 'task3-2d664',
    storageBucket: 'task3-2d664.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCAf81TokSLT3fnVnOJkr1thoBw9xSFOs',
    appId: '1:50269195141:ios:f50272e2eb21a1fc7152ec',
    messagingSenderId: '50269195141',
    projectId: 'task3-2d664',
    storageBucket: 'task3-2d664.appspot.com',
    iosClientId: '50269195141-qpj4d86s7jfqng51v041k2hh2vktfaqr.apps.googleusercontent.com',
    iosBundleId: 'com.example.task1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCAf81TokSLT3fnVnOJkr1thoBw9xSFOs',
    appId: '1:50269195141:ios:f50272e2eb21a1fc7152ec',
    messagingSenderId: '50269195141',
    projectId: 'task3-2d664',
    storageBucket: 'task3-2d664.appspot.com',
    iosClientId: '50269195141-qpj4d86s7jfqng51v041k2hh2vktfaqr.apps.googleusercontent.com',
    iosBundleId: 'com.example.task1',
  );
}
